---
version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    hostname: kafka
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.6
      KAFKA_CREATE_TOPICS: "runs:3:1,run_messages:1:1,run_statuses:1:1:compact,run_logs:1:1,run_files:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  postgres:
    image: postgres:12.2
    hostname: postgres-db
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "darko"
      POSTGRES_PASSWORD: "darko"
      POSTGRES_DB: "drboson"
    volumes:
      - /Users/darko/Documents/Projects/databases/drboson:/var/lib/postgresql/data
      